current set of scripts run to repair the coadd production

diff --git a/workflows/srs/pipe_setups/run_coaddDriver b/workflows/srs/pipe_setups/run_coaddDriver
--- a/workflows/srs/pipe_setups/run_coaddDriver
+++ b/workflows/srs/pipe_setups/run_coaddDriver
@@ -12,16 +12,52 @@ echo "Working on TRACT=${TRACT}, PATCH=${PATCH}, FILT=${FILT}"
 visit_file=${FILEDIR}/${TRACT}_${PATCH}_${FILT}_visits.list 
 
 if [ $FILT = u ]; then
-    echo "coaddDriver.py ${OUT_DIR} --rerun ${RERUN1}:${RERUN2}-u --id tract=${TRACT} patch=${PATCH} filter=$FILT @${visit_file} --cores $((NSLOTS+1)) --longlog --configfile=${OBS_LSST_DIR}/config/coaddDriver_noPSF.py --reuse-outputs-from  all"
-    coaddDriver.py ${OUT_DIR} --rerun ${RERUN1}:${RERUN2}-u --id tract=${TRACT} patch=${PATCH} filter=$FILT @${visit_file} --cores $((NSLOTS+1)) --longlog --configfile=${OBS_LSST_DIR}/config/coaddDriver_noPSF.py --reuse-outputs-from  all
+    cd $TMPDIR
+    cmd="coaddDriver.py ${OUT_DIR} --rerun ${RERUN1}:${RERUN2}-u --id tract=${TRACT} patch=${PATCH} filter=$FILT @${visit_file} --cores $((NSLOTS+1)) --longlog --configfile=${OBS_LSST_DIR}/config/coaddDriver_noPSF.py --reuse-outputs-from  all --doraise"
+    echo $cmd;$cmd
+    if [[ $? == 0 ]]; then
+	echo "successful execution of ${cmd}"
+    else 
+	echo "failure in execution of ${cmd}"
+	exit 1
+    fi
+    for patch in ${PATCH//^/ }; do
+	warpdir="${OUT_DIR}/rerun/${RERUN2}-u/deepCoadd/$FILT/$TRACT/$patch"
+	if [[ -d ${warpdir} && -f ${warpdir}/../$patch.fits ]]; then
+    	    echo "removing warps in ${warpdir}"
+    	    #rm -r ${warpdir}
+	fi
+    done
 else
-    echo "coaddDriver.py ${OUT_DIR} --rerun ${RERUN1}:${RERUN2}-grizy --id tract=${TRACT} patch=${PATCH} filter=$FILT @${visit_file} --cores $((NSLOTS+1)) --longlog --reuse-outputs-from  all"
-    coaddDriver.py ${OUT_DIR} --rerun ${RERUN1}:${RERUN2}-grizy --id tract=${TRACT} patch=${PATCH} filter=$FILT @${visit_file} --cores $((NSLOTS+1)) --longlog --reuse-outputs-from  all
+    cd ${TMPDIR}
+    cmd="coaddDriver.py ${OUT_DIR} --rerun ${RERUN1}:${RERUN2}-grizy --id tract=${TRACT} patch=${PATCH} filter=$FILT @${visit_file} --cores $((NSLOTS+1)) --longlog --reuse-outputs-from  all --doraise"
+    echo $cmd;$cmd;
+    if [[ $? == 0 ]]; then
+	echo "successful execution of ${cmd}"
+    else 
+	echo "failure in execution of ${cmd}"
+	exit 1
+    fi
+    for patch in ${PATCH//^/ }; do
+	warpdir="${OUT_DIR}/rerun/${RERUN2}-grizy/deepCoadd/$FILT/$TRACT/$patch"
+        if [[ -d ${warpdir} && -f ${warpdir}/../$patch.fits ]]; then
+            echo "removing warps in ${warpdir}"
+            #rm -r ${warpdir}
+        fi
+    done
 fi
 
-echo "grep \"Caught FitsError while coadding DataId\"  ${JOBCONTROL_LOGFILE}"
-out=`grep  "Caught FitsError while coadding DataId" ${JOBCONTROL_LOGFILE}`
-if [[ ! -z $out ]];then 
-    echo "Traceback detected... exiting with error"
-    exit 1
+mkdir -p ${OUT_DIR}/expmaps/${TRACT} 
+cd ${TMPDIR}
+echo "executing supreme...."
+for p in $(echo ${PATCH} | tr "^" "\n"); do
+    cmd=${ROOT_SOFTS}/bin/supreme_map_patch.py -c ${OUT_DIR}/expmaps/config_quick.yml -r ${OUT_DIR}/rerun/${RERUN2} -t ${TRACT} -f $FILT -p $p -o ${OUT_DIR}/expmaps/${TRACT}/
+    mv *.hs ${OUT_DIR}/expmaps/${TRACT}/.
+    echo $cmd;$cmd
+done
+if [[ $? == 0 ]]; then
+  echo "successful execution of ${cmd}"
+else
+  echo "failure in execution of ${cmd}"
+  exit 1
 fi
diff --git a/workflows/srs/pipe_setups/run_multiband b/workflows/srs/pipe_setups/run_multiband
--- a/workflows/srs/pipe_setups/run_multiband
+++ b/workflows/srs/pipe_setups/run_multiband
@@ -8,6 +8,23 @@ then
     /pbs/home/d/descprod/bin/joremon.sh
 fi
 
-cmd="multiBandDriver.py ${OUT_DIR} --rerun ${RERUN2} --id tract=${TRACT} patch=${PATCH} filter=${FILTERS//,/^} --cores=$((NSLOTS+1)) --longlog --reuse-outputs-from  all"
+cd ${TMPDIR}
+cmd="multiBandDriver.py ${OUT_DIR} --rerun ${RERUN2} --id tract=${TRACT} patch=${PATCH} filter=${FILTERS//,/^} --cores=$((NSLOTS+1)) --longlog --reuse-outputs-from  all --doraise"
 echo $cmd;$cmd
 
+if [[ $? == 0 ]]; then
+    rc=0
+    for patch in ${PATCH//^/ }; do
+	outref=${OUT_DIR}/rerun/${RERUN2}/deepCoadd-results/merged/${TRACT}/${patch}/ref-${TRACT}-${patch}.fits
+	if [[ ! -f ${outref} ]]; then
+	    echo "${outref} not found; multiband execution likely failed."
+	    status=1
+	fi
+    done
+    if [[ $rc == 0 ]]; then
+	echo "successful execution of ${cmd}"
+    else
+	echo "failure in execution of ${cmd}" 
+	exit rc
+    fi
+fi
diff --git a/workflows/srs/pipe_setups/setup_coaddDriver b/workflows/srs/pipe_setups/setup_coaddDriver
--- a/workflows/srs/pipe_setups/setup_coaddDriver
+++ b/workflows/srs/pipe_setups/setup_coaddDriver
@@ -7,9 +7,12 @@ IFS='^' read -ra array <<< ${PATCH}
 patch_str="(";for d in ${array[@]}; do patch_str+="patch='(${d//,/, })' or ";done
 patch_str=${patch_str::-4}\)
 
+#copy the db locally to avoid hitting the FS
+cp ${OUT_DIR}/rerun/${RERUN1}/tracts_mapping.sqlite3 ${TMPDIR}/
+
 for FILT in $(echo ${FILTERS} | tr "," "\n")
 do
-    visit_list=`sqlite3 ${OUT_DIR}/rerun/${RERUN1}/tracts_mapping.sqlite3 "SELECT DISTINCT visit FROM overlaps WHERE tract=${TRACT} and filter='${FILT}' and ${patch_str}"`
+    visit_list=`sqlite3 ${TMPDIR}/tracts_mapping.sqlite3 "SELECT DISTINCT visit FROM overlaps WHERE tract=${TRACT} and filter='${FILT}' and ${patch_str}"`
     echo $visit_list
 
     if [[ -z "${COADD_VISITS}" ]]; then
@@ -17,8 +20,8 @@ do
     else
 	comm -12 <(sort ${COADD_VISITS}) <(sort <<<"${visit_list[*]}")
 	usable_visits=`comm -12 <(sort ${COADD_VISITS}) <(sort <<<"${visit_list[*]}")`
+	echo "usable visits: ${usable_visits}"
     fi
-    echo "usable visits: ${usable_visits}"
 
     if [[ ! -z "${usable_visits}" ]]; then
 	visit_file=${WORKDIR}/${streamID}/${TRACT}_${PATCH}_${FILT}_visits.list
@@ -27,10 +30,18 @@ do
 	fi
 	touch ${visit_file}
 	for line in $usable_visits; do
-	    detector_list=`sqlite3 ${OUT_DIR}/rerun/${RERUN1}/tracts_mapping.sqlite3 "SELECT DISTINCT detector FROM overlaps WHERE visit=${line} and tract=${TRACT} and filter='${FILT}' and ${patch_str}"`
+	    detector_list=`sqlite3 ${TMPDIR}/tracts_mapping.sqlite3 "SELECT DISTINCT detector FROM overlaps WHERE visit=${line} and tract=${TRACT} and filter='${FILT}' and ${patch_str}"`
 	    #IFS="|" read visit detector <<< $line
 	    for detector in $detector_list; do
-		echo "--selectId visit=$line detector=$detector">>${visit_file}
+		#kludge : check that the sky correction exists
+		visit=$( printf "%08d" $line )
+		det=$( printf "%03d" $detector )
+		dummy=`ls ${OUT_DIR}/rerun/${RERUN1}/calexp_camera/${visit}-${FILT}/*/calexp_camera_${visit}-${FILT}*det${det}.fits`
+		if [[ $? == 0 ]]; then
+		    echo "--selectId visit=$line detector=$detector">>${visit_file}
+		else
+		    echo "discarding visit=$line detector=${detector}"
+		fi
 	    done
 	done
 	echo pipelineCreateStream task_coaddDriver "FILT="\""${FILT}"\"",FILEDIR="\""${FILEDIR}"\"""
@@ -39,3 +50,10 @@ do
 	echo "No visit match the requested tract/patch/filter"
     fi
 done
+
+if [[ $? == 0 ]]; then
+  echo 'success'
+else
+  echo 'error'
+  exit 1
+fi
