rationalize execution of makeSkyMap defer copying tracts_mapping.sqlite3

diff --git a/workflows/srs/pipe_setups/setup_calexp b/workflows/srs/pipe_setups/setup_calexp
--- a/workflows/srs/pipe_setups/setup_calexp
+++ b/workflows/srs/pipe_setups/setup_calexp
@@ -12,12 +12,19 @@ export WORKDIR
 
 #start by building the skymap as it is needed for the tract/patch mapping DB construction
 
-if [ ! -d "$IN_DIR/rerun/$RERUN2/deepCoadd" ]; then
-    makeSkyMap.py ${IN_DIR} --rerun ${RERUN}
-    cp -r $IN_DIR/rerun/$RERUN2/deepCoadd $IN_DIR/rerun/$RERUN1/
+if [ ! -d "$IN_DIR/rerun/${RERUN1}/deepCoadd" ]; then
+    #deepCoadd dir is created by the first execution of makeSkyMap.py
+    echo "makeSkyMap.py ${IN_DIR} --rerun ${RERUN1}"
+    makeSkyMap.py ${IN_DIR} --rerun ${RERUN1}
+    #cp -r $IN_DIR/rerun/${RERUN2}/deepCoadd $IN_DIR/rerun/${RERUN1}/
     #turn the absolute path into a relative one for the root entry in the yaml file, to ease shipping to NERSC
     #we need to do that at the end 
     #sed -i -e 's+'${IN_DIR}'+..\/..+g' ${IN_DIR}/rerun/$RERUN2/repositoryCfg.yaml
+fi
+
+if [ ! -d "$IN_DIR/rerun/${RERUN1}/deepCoadd" ]; then
+    echo "makeSkyMap.py failed, forcing exit"
+    exit 1
 fi
 
 if [[ -z "${VISIT_FILE}" ]]; then
